Swe_HDpatient_homepage:
      path: /
      defaults: {_controller: SweHDBundle:HDPatient:index}

Swe_HDpatient_new:
      path: /new
      defaults: {_controller: SweHDBundle:HDPatient:new}

Swe_HDpatient_show:
      path: /{id}
      defaults: {_controller: SweHDBundle:HDPatient:show}

Swe_HDpatient_edit:
      path: /{id}/edit
      defaults: {_controller: SweHDBundle:HDPatient:edit}

Swe_HDpatient_delete:
      path: /delete/{id}
      defaults: {_controller: SweHDBundle:HDPatient:delete}
